spring:
  application:
    name: Bank_REST
  profiles:
    active: dev

server:
  port: 8080

springdoc:
  api-docs:
    path: /docs/openapi.yaml
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha


security:
  jwt:
    secret: ${JWT_SECRET:53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855}
    expiration: 86400000